---
# tasks file for web_server
- block: #Debian
  - name: Install apache2 Debian
    apt: name=apache2

  - name: Generate index.html
    template:
      src: "index.j2"
      dest: "{{destin_folder}}/index.html"
      mode: 0644
    notify: Restart Apache Debian

  - name: Upload web-site Debian
    copy: src={{ item }} dest={{destin_folder}} mode=0644
    loop: 
      - cat1.jpg
      - cat2.jpg
    notify: Restart Apache Debian

  - name: StArt apache2 Debian
    service:
      name: apache2
      state: started
      enabled: yes
  when: ansible_os_family=="Debian"

- block: #RedOS
  - name: Install apache2 RedOS
    dnf: name=httpd

  - name: Generate index.html
    template:
      src: "index.j2"
      dest: "{{destin_folder}}/index.html"
      mode: 0644
    notify: Restart Apache RedOS

  - name: Upload web-site RedOS
    copy: src={{item}} dest={{destin_folder}} mode=0644
    with_fileglob: "files/*"
    notify: Restart Apache RedOS

  - name: StArt apache2 RedOS
    service:
      name: httpd
      state: started
      enabled: yes

  when: ansible_os_family=="RED"