---
- name: Loops
  hosts: client1
  become: yes

  tasks:
  - name: Say Hello
    debug: msg="Hello {{ item }}"
    loop:
      - "Vasya"
      - "Petya"
      - "Masha"

  - name: loop until
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 3
    retries: 10
    until: output.stdout.find("ZZZZZ") == false

  - name:
    debug:
      var: output