---
- name: Install apache2 and upload web-siTe
  hosts: client2
  become: yes

  vars:
    source_file: ./index.html
    destin_file: /var/www/html

  tasks:
  - name: Install apache2
    apt: name=apache2

  - name: Upload web-siTe
    copy: src={{source_file}} dest={{destin_file}} mode=0644
    notify: Restart Apache

  - name: StArt apache2
    service:
      name: apache2
      state: started
      enabled: yes
    
  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted